version: '2'

services:
  nginx:
    build: ./docker/nginx/
    ports:
    - 80:80
    links:
    - php7
    volumes_from:
    - app

  php7:
    build: ./docker/php/php7/
    expose:
    - 9000
    volumes_from:
    - app

  app:
    image: php:7.1-fpm
    volumes:
    - /Users/joeblack/Documents/www/timesheet-manager:/var/www/html
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    command: "true"